DE-115 sql-kata -> Earthly build script
OptimaJetLLC/querybuilder pull request #15
Opened 2024-05-01 09:05 UTC by rylee-soll

+ Пришлось обновить пакет с SQL из-за олчень страшных сообщений об уязвимости у меня не собирался солюшн

2024-05-01 09:12 UTC, rylee-soll commented on Earthfile
> +  RUN dotnet build ./SqlKata.Execution/SqlKata.Execution.csproj -c Release -o /build
It's not explicitly stated here, but when building this package, the main package is also built

2024-05-01 11:46 UTC, shalugin requested changes

2024-05-01 11:46 UTC, shalugin commented on Earthfile
> +publish-sqlkata-nuget:
Rename it to `publish-artifact-sqlkata-nuget`. And we need a task to publish the nuget package from local files, name it `publish-archive-sqlkata-nuget`.

2024-05-02 09:29 UTC, shalugin approved these changes

2024-05-02 09:29 UTC, merged